# Generated by Django 6.0.3 on 2026-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='absent', max_length=10),
        ),
    ]
