# Generated by Django 6.0.3 on 2026-04-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_classes', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
