# Generated by Django 6.0.3 on 2026-04-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_academicyearconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_classes',
            field=models.IntegerField(default=40),
        ),
    ]
