# Generated by Django 6.0.3 on 2026-04-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_subject_total_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
    ]
