# Generated by Django 6.0.3 on 2026-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_studentprofile_current_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
