# Generated by Django 6.0.3 on 2026-04-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_studentprofile_current_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='target_percentage',
            field=models.IntegerField(default=75),
        ),
    ]
