# Generated by Django 6.0.3 on 2026-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_academiccalendar_studenttimetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academiccalendar',
            name='holidays_json',
        ),
        migrations.RemoveField(
            model_name='academiccalendar',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='academiccalendar',
            name='start_date',
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem1_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem2_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem3_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem4_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem5_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem6_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem7_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='sem8_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
