# Generated by Django 6.0.3 on 2026-04-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_academiccalendar_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='total_attendance_points',
        ),
    ]
