# Generated by Django 6.0.3 on 2026-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_studentprofile_total_attendance_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttimetable',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
