# Generated by Django 6.0.3 on 2026-04-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_studenttimetable_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='semester',
        ),
    ]
