# Generated by Django 6.0.3 on 2026-04-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remove_holiday_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='holiday_list_image',
            field=models.ImageField(blank=True, null=True, upload_to='holiday_lists/'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='holidays_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
