# Generated by Django 6.0.3 on 2026-04-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_extraholidayreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='total_classes',
            field=models.IntegerField(default=40),
        ),
    ]
