# Generated by Django 6.0.3 on 2026-04-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_enrollment_total_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='units',
            field=models.IntegerField(default=1, help_text='Number of class units (e.g., 2 for double theory, 1 for lab)'),
        ),
    ]
