# Generated by Django 6.0.3 on 2026-04-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendance_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttimetable',
            name='timetable_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttimetable',
            name='timetable_image',
            field=models.ImageField(blank=True, null=True, upload_to='timetables/'),
        ),
    ]
